name: OMB tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Spack
        uses: spack/setup-spack@v2
        with:
          ref: develop # Spack version (examples: develop, releases/v0.23)
          color: true # Force color output (SPACK_COLOR=always)
          path: spack-src # Where to clone Spack

      - name: Build and install
        shell: spack-bash {0}
        run: |
          spack install -j 4 --use-buildcache=package:never,dependencies:auto osu-micro-benchmarks

      - name: Run a OSU program multi-line script
        run: |
          spack load osu-micro-benchmarks
          mpiexec -n 3 $(spack location -i osu-micro-benchmarks)libexec/osu-micro-benchmarks/mpi/startup/osu_hello
